---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: utility
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  # Depends on having the sealed secret to un-encrypted required secrets.
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    existingSecret: minio-secret
    persistence:
      existingClaim: nfs-data-franxx
      subPath: minio
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 0
      hosts:
        - s3.56k.jp
        - s.56k.jp
      tls:
        - hosts:
            - s3.56k.jp
            - s.56k.jp
