---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: utility
spec:
  interval: 5m
  chart:
    spec:
      chart: bitwardenrs
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # Depends on having the sealed secret to un-encrypted required secrets.
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    image:
      repository: bitwardenrs/server
      tag: 1.20.0
    fullnameOverride: bitwarden
    bitwardenrs:
      domain: "https://password.56k.jp"
      admin:
        existingSecret:
          enabled: true
          name: "bitwarden-admin"
          tokenKey: "admin-token"
      smtp:
        enabled: true
        from: "bitwarden@56k.jp"
        fromName: "56k Bitwarden"
        existingSecret:
          enabled: true
          name: "bitwarden-smtp"
          userKey: "smtp-user"
          passwordKey: "smtp-password"
    persistence:
      enabled: true
      size: 10Gi
    ingress:
      enabled: true
      hosts:
        - host: "password.56k.jp"
          paths: ["/"]
      tls:
        - hosts:
            - "password.56k.jp"
  valuesFrom:
    - kind: Secret
      name: "bitwarden-helm-values"
